version: '3.1'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    depends_on: 
      - db    

  db:
    image: mysql:8.0.15        
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password    

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app