version: '3.1'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    restart: always
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    depends_on: 
      - db    

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password    

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app